### ISSUE TITLE
Link to Genesis Framework gives a 404

### ISSUE THREAD

**Issue by RRWD** [defries/genesis-translations#2]
Link to Genesis in the string
Whoa.. the translation this plugin only works, really, when you have installed the Genesis Framework
goes to: https://forsite.media/en/go/genesis/
Which gives a 404 page.

**Comment by defries** [comment]
Whoa.. that's not supposed to happen. I'll have this fixed in the next release. Thanks @RRWD :)

**Comment by defries** [comment]
Also put a proper redirect in place for now.
